#12. Read Integer (N) and Print the First Three Powers(N^1,N^2, N^3)
integer = int(input("Enter a Number"))
print("Given number: ", pow(integer,1))
print("Square of given number: ", pow(integer,2))
print("Cube of given number : ", pow(integer,3))